import {ArrowUpRight,Building2,Headphones,House,Radio,Zap} from 'lucide-react';
import {Hero} from '@/components/home/Hero';
import {SupportOrbit} from '@/components/home/SupportOrbit';
import {SectionHeading} from '@/components/shared/SectionHeading';
import {EnquiryForm} from '@/components/forms/EnquiryForm';
import {PricingGrid} from '@/components/shared/PricingGrid';
import {Button} from '@/components/shared/Button';
import {ZifiFiberLine} from '@/components/brand/ZifiFiberLine';
import {NetworkDots} from '@/components/brand/NetworkDots';
import {pageMetadata,site} from '@/lib/site';
import {businessAddress} from '@/data/terms';

export const metadata=pageMetadata('Fiber Internet in Surat','Fast, reliable fiber broadband for modern homes and businesses in Surat. Explore Mandala Broadband plans and check local availability.');
const features=[[Zap,'Fast fiber connectivity','Speed that keeps up with streaming, work and every connected device.'],[Headphones,'24/7 support','Human help when you need it, built into the Mandala Broadband experience.'],[House,'Built for modern homes','A stable foundation for the way your household lives online.'],[Building2,'Business-ready connectivity','Scalable, professional internet for growing teams.']];
const services=[[House,'Home Broadband','Smooth everyday internet designed around your household.'],[Radio,'Fiber Internet','Low-latency fiber with room for everything you do online.'],[Building2,'Business Broadband','Connectivity that can grow with your operation.'],[Headphones,'Dedicated Support','Clear assistance across setup, billing and connectivity.']];

export default function Home(){const schema={"@context":"https://schema.org","@type":["LocalBusiness","InternetServiceProvider"],name:'Mandala Broadband',url:site.url,areaServed:{"@type":"City",name:'Surat'},email:'hariom09shukla@gmail.com',telephone:'9898955323',address:{"@type":"PostalAddress",streetAddress:businessAddress,addressLocality:'Surat',postalCode:'395023',addressRegion:'Gujarat',addressCountry:'IN'}};return <>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(schema)}}/>
  <Hero/>
  <section className="section bg-gradient-to-b from-sky-50 via-blue-50/50 to-white dark:from-blue-950/35 dark:via-panel dark:to-panel"><div className="container-x"><SectionHeading eyebrow="Why Mandala Broadband" title="Internet engineered around real life." copy="A modern connectivity experience with the performance, support and simplicity you expect."/><ZifiFiberLine className="my-8"/><div className="grid gap-5 md:grid-cols-2 lg:grid-cols-4">{features.map(([Icon,t,c],i)=><article className={`card feature-card p-7 ${['feature-ice','feature-cobalt','feature-azure','feature-navy'][i]}`} key={t as string}><span className="feature-number text-xs font-extrabold tracking-widest">0{i+1}</span><div className="feature-icon mt-8 flex h-11 w-11 items-center justify-center rounded-xl"><Icon size={22}/></div><h3 className="mt-6 text-h3">{t as string}</h3><p className="muted mt-3 text-sm leading-6">{c as string}</p></article>)}</div></div></section>
  <section className="section"><div className="container-x"><SectionHeading eyebrow="Plans" title="A faster plan for every kind of connected life." copy="Straightforward speeds. Thoughtful support. No confusing plan names."/><div className="mt-12"><PricingGrid showAudience={false}/></div></div></section>  <section className="section"><div className="container-x"><SectionHeading eyebrow="Services" title="One network. More ways to connect."/><div className="mt-12 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{services.map(([Icon,t,c])=><a href="/services" key={t as string} className="group card relative overflow-hidden p-7"><div className="absolute inset-0 grid-fade opacity-0 transition group-hover:opacity-100"/><Icon className="relative text-brand"/><h3 className="relative mt-16 text-h3">{t as string}</h3><p className="relative muted mt-3 text-sm leading-6">{c as string}</p><ArrowUpRight className="relative mt-6 text-brand transition-transform group-hover:translate-x-1 group-hover:-translate-y-1"/></a>)}</div></div></section>
  <section className="section overflow-hidden bg-brand text-white"><div className="container-x grid items-center gap-12 lg:grid-cols-2"><div><span className="eyebrow text-white before:bg-white">Built for Surat</span><h2 className="mt-5 text-h2">Built for Surat. Ready for what’s next.</h2><p className="mt-6 max-w-xl text-blue-100">Mandala Broadband is building a reliable connectivity experience for homes and businesses across Surat.</p><Button href="/coverage" variant="secondary" className="mt-8">Check your area</Button></div><NetworkVisual/></div></section>
  <section className="section bg-night text-white"><div className="container-x grid items-center gap-12 lg:grid-cols-2"><NetworkVisual/><div><span className="eyebrow text-brand-cyan before:bg-brand-cyan">Mandala Broadband Business</span><h2 className="mt-5 text-h2">Internet that keeps your business moving.</h2><p className="mt-6 text-slate-300">Business-grade connectivity, priority support, scalable plans and reliable performance for ambitious teams.</p><Button href="/business-broadband" className="mt-8">Talk to business team</Button></div></div></section>
  <section className="section overflow-hidden"><div className="container-x grid items-center gap-10 lg:grid-cols-2"><SupportOrbit/><div><p className="text-[clamp(5rem,16vw,11rem)] font-extrabold leading-none text-brand">24/7</p><h2 className="mt-2 text-h2">We’re here when you need us.</h2><p className="muted mt-5 text-lg">Support · Assistance · Connectivity</p></div></div></section>
  <section className="section bg-white dark:bg-panel"><div className="container-x"><SectionHeading eyebrow="Launch metrics" title="A company built around connection."/><div className="mt-10 grid gap-4 sm:grid-cols-3">{[['X','homes connected'],['X%','uptime target'],['Y','years serving Surat']].map(([n,l])=><div className="card p-8" key={l}><strong className="text-4xl text-brand">{n}</strong><p className="muted mt-2">{l}</p></div>)}</div><p className="muted mt-4 text-xs">Placeholder metrics — replace with verified business data before launch.</p></div></section>
  <section className="section relative overflow-hidden bg-ink text-white"><NetworkDots className="opacity-40"/><div className="container-x relative"><SectionHeading eyebrow="Enquire now" title="Ready for a better connection?" copy="Tell us what you need and where you are. The Mandala Broadband team will help with the next step."/><div className="mt-10 text-ink dark:text-white"><EnquiryForm/></div></div></section>
</>}

function NetworkVisual(){return <div className="relative min-h-80 overflow-hidden rounded-3xl border border-white/15 bg-white/5"><div className="absolute inset-0 bg-grid bg-[size:40px_40px]"/><NetworkDots/><svg viewBox="0 0 500 300" className="absolute inset-0 h-full w-full" aria-label="Abstract network connecting areas across Surat"><g stroke="#35C8FF" strokeWidth="1" opacity=".55"><path d="M70 220L170 130 270 195 390 80M170 130L310 70M270 195L430 230"/></g>{[[70,220],[170,130],[270,195],[390,80],[310,70],[430,230]].map(([x,y],i)=><g key={i}><circle cx={x} cy={y} r="14" fill="#1769FF" opacity=".18"><animate attributeName="r" values="9;16;9" dur={`${2.4+i*.18}s`} repeatCount="indefinite"/></circle><circle cx={x} cy={y} r="4" fill="#fff"/></g>)}</svg><div className="absolute bottom-6 left-6 rounded-full border border-white/15 bg-night/70 px-4 py-2 text-xs text-white backdrop-blur">Surat network visualization</div></div>}
